Repository talonhub/community, pull requests merged in 2021-10, with the labels that each got.

#590 fix tab_next and tab_right shortcuts for MacOS
  code/platforms/mac/app.py
Labels: bug, MacOS

#587 Fix macOS Slack unread command
  apps/slack/slack_mac.talon
Labels: bug, MacOS

#568 Apple terminal: cleanup & migrate to generic_unix_shell commands
  apps/platforms/mac/terminal/apple_terminal.py
  apps/platforms/mac/terminal/apple_terminal.talon
  apps/platforms/mac/terminal/terminal.talon
Labels: enhancement, MacOS

#601 Improve WSL error logging
  apps/platforms/win/wsl/wsl.py
  code/file_manager.py
Labels: bug, Windows

#576 Add better support for the java programming language
  code/code.py
  lang/java/java.py
  lang/java/java.talon
  lang/operators.talon
Labels: enhancement
