Repository talonhub/community, pull requests merged in 2021-11, with the labels that each got.

#631 Parse url from browser title
  apps/web/github.talon
  apps/web/gitlab.talon
  apps/web/twitter.talon
  apps/web/window_titles.md
  code/browser.py
Labels: enhancement

#623 deprecate "m grid" for "mouse grid" forget tag
  README.md
  mouse_grid/mouse_grid.py
  mouse_grid/mouse_grid.talon
  mouse_grid/mouse_grid_always.talon
  settings.talon
Labels: enhancement

#627 Improve snap to vertical screen
  code/window_snap.py
Labels: enhancement

#643 web: Explain what to configure in window titles
  apps/web/window_titles.md
Labels: documentation

#638 Fix issue with initial continuous scroll speed
  code/mouse.py
Labels: bug

#655 fix safari shortcuts
  apps/platforms/mac/sarafi/safari.py
Labels: bug, MacOS

#661 create_spoken_forms.py: use Any instead of T
  code/create_spoken_forms.py
Labels: bug

#652 Break up code.py into one file per tag
  README.md
  apps/generic_snippets/generic_snippets.py
  apps/generic_snippets/generic_snippets.talon
  code/code.py
  lang/go/go.talon
  lang/sql/sql.talon
  lang/tags/block_comment.py
  lang/tags/block_comment.talon
  lang/tags/comment.py
  lang/tags/comment.talon
  lang/tags/generic.py
  lang/tags/generic.talon
  lang/tags/operators.py
  lang/tags/operators.talon
  modes/language_modes.talon
Labels: enhancement

#653 Jetbrains - tag:multiple_cursors and tag:splits implementation
  apps/jetbrains/jetbrains.py
  apps/platforms/mac/datagrip.talon
Labels: enhancement, jetbrains

#646 [Windows] Improve app launching
  code/switcher.py
Labels: enhancement, Windows

#659 numbers.py: disallow leading scale words
  code/numbers.py
Labels: bug
