Repository talonhub/community, pull requests merged in 2022-02, with the labels that each got.

#730 Add emoji tag
  apps/discord/discord.talon
  apps/discord/mac.py
  apps/discord/win.py
  apps/slack/slack_mac.talon
  apps/slack/slack_win.talon
  emoji/emoji.csv
  emoji/emoji.py
  emoji/emoji.talon
  emoji/emoticon.csv
  emoji/kaomoji.csv
Labels: enhancement

#739 Fix watchdogs when getting page address in Safari
  apps/platforms/mac/safari/safari.py
Labels: bug, MacOS, needs validation

#742 make "go <arrows>" use edit.left, allow "press <keys>" for arrow keys instead
  code/keys.py
  misc/keys.talon
  modes/dictation_mode.talon
Labels: enhancement

#752 Add support for terraform
  apps/terraform/terraform.py
  apps/terraform/terraform.talon
  code/code.py
  lang/terraform/terraform.py
  lang/terraform/terraform.talon
  modes/language_modes.talon
Labels: enhancement

#632 Add support for controlling multiple WSL distros and prune one error …
  apps/platforms/win/wsl/ubuntu.talon
  apps/platforms/win/wsl/wsl.py
  apps/platforms/win/wsl/wsl.talon
Labels: enhancement, waiting

#758 Improve phrase history mechanism
  code/history.py
Labels: enhancement

#767 formatters.py: reorg/simplify a bit
  code/formatters.py
Labels: enhancement

#763 simplify _capitalize_defaults
  code/vocabulary.py
Labels: enhancement

#744 Remove redundant `ctrl` press from Mac screenshots
  code/screenshot.py
Labels: enhancement, MacOS, needs validation

#738 Handle capitalization of e.g. and i.e. within prose.
  code/dictation.py
  tests/test_dictation.py
Labels: enhancement

#735 Scala support
  code/code.py
  lang/scala/scala.py
  lang/scala/scala.talon
  modes/language_modes.talon
Labels: enhancement

#745 Add command to open screenshot settings
  code/screenshot.py
  misc/screenshot.talon
Labels: enhancement

#743 Add Rust support
  code/code.py
  lang/rust/rust.py
  lang/rust/rust.talon
  modes/language_modes.talon
Labels: enhancement
